# Generated by Django 2.1.2 on 2018-11-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sit', '0002_auto_20181103_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
