# Generated by Django 2.1.2 on 2018-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sit', '0003_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='uni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30, null=True)),
                ('cpera', models.TextField()),
                ('chname', models.CharField(max_length=30)),
                ('chist', models.CharField(max_length=200)),
                ('achiv', models.CharField(max_length=30)),
                ('achivhis', models.CharField(max_length=200)),
                ('depart', models.CharField(max_length=30)),
                ('departhis', models.CharField(max_length=200)),
            ],
        ),
    ]
